public class DailyTasks {
    public static void eatBreakfast(){
        system.debug('the person eat breakfast');
    }
    @future public static void getBikeServiced(){
        system.debug('the bike should be serviced ');
    }
    public static void attenConferenceCall(){
        system.debug('please attend thge conference call');
    }
    public static void performDailyTasks(){
        eatBreakfast();
        getBikeServiced();
        attenConferenceCall();
         }
}